### ISSUE TITLE
Image URL 

### ISSUE THREAD

**Issue by pracasupreti** [pracasupreti/SRIYOG.js#2]
Current Image URL : https://sriyogreact.vercel.app/_next/image?url=%2Fimages%2Fhome%2Ftop%2F2.png&w=256&q=75

Fix and make like : https://domain.com/profile/9779807066550.png @GaurabGogo

**Comment by GaurabGogo** [comment]
Fixed the issue for temporarily because nextjs uses optimized images to lazy load the image which makes the website faster. using the <img> tag to fix the current issue to view the real link of image.
